name: Build ML Dataset

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build-ml-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run gap and go ML dataset script
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python Backtesting/gap_and_go_ml_ready.py

      - name: Upload yearly ML datasets
        uses: actions/upload-artifact@v4
        with:
          name: gap_and_go_yearly_ml_data
          path: data/*-data.csv
