name: Penny Stock Backtest

on:
  workflow_dispatch:  # Manual run option
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: List repo contents (debug)
        run: ls -R

      - name: Run penny stock backtest
        run: python scripts/gap_and_go_backtest.py

      - name: Upload backtest CSVs
        uses: actions/upload-artifact@v4
        with:
          name: backtest-csvs
          path: data/
