name: Penny Stock Backtest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run backtest script
        run: python backtest_penny_stocks.py

      - name: Configure Git for commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push updated CSVs
        run: |
          git add data/*.csv
          git commit -m "Auto-update backtest CSVs [skip ci]" || echo "No changes to commit"
          git push
