name: Penny Stock Backtest

on:
  workflow_dispatch:  # Allow manual triggering from GitHub UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run penny stock backtest
        run: python your_script_name.py  # Replace with actual filename

      - name: Upload data folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backtest-csvs
          path: data/
