name: Run Gap and Go Backtest

on:
  workflow_dispatch:

jobs:
  gap-and-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas

      - name: Ensure data directory exists
        run: |
          mkdir -p data

      - name: Merge monthly CSVs into yearly files
        run: |
          echo "Merging monthly CSV files into yearly..."
          python scripts/merge_monthly_to_yearly.py

      - name: Run gap_and_go backtest
        run: |
          echo "Running gap_and_go_backtest.py..."
          python Backtesting/gap_and_go_backtest.py
