name: Build ML Dataset

on:
  workflow_dispatch:  # Allows manual triggering from GitHub

jobs:
  build-ml-dataset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run dataset builder
        run: |
          python scripts/build_ml_dataset.py

      - name: Upload ML dataset
        uses: actions/upload-artifact@v4
        with:
          name: gap_and_go_ml_dataset
          path: Backtesting/results/gap_and_go_ml_dataset.csv
