name: Fetch Polygon Data

on:
  workflow_dispatch:  # allows manual trigger from GitHub Actions tab

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run fetch script
        run: |
          python scripts/fetch_polygon_data.py
