name: Run Gap and Go Engine

on:
  workflow_dispatch:

jobs:
  gap-and-go-backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pandas numpy matplotlib

      - name: Run Gap and Go Engine
        run: |
          echo "Running gap_and_go_backtest.py..."
          python Backtesting/gap_and_go_backtest.py

      - name: Upload Summary CSV
        uses: actions/upload-artifact@v3
        with:
          name: gap-and-go-summary
          path: Backtesting/gap_and_go_summary.csv

      - name: Upload Performance Charts
        uses: actions/upload-artifact@v3
        with:
          name: gap-and-go-charts
          path: Backtesting/plots/
